function anogigi(X1, Y1)
%CREATEFIGURE1(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 01-Oct-2013 15:16:39

% Create figure
figure1 = figure('PaperSize',[20.98404194812 29.67743169791]);

% Create axes
axes1 = axes('Parent',figure1,...
    'YTick',[0.07 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1],...
    'YGrid','on',...
    'XGrid','on');
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'MarkerFaceColor',[0 0 1],'MarkerEdgeColor',[0 0 1],...
    'MarkerSize',8,...
    'Marker','.',...
    'LineWidth',0.7,...
    'LineStyle',':',...
    'Color',[0 0 0]);

% Create xlabel
xlabel('Pompate');

% Create ylabel
ylabel('Pressioni');

% Create title
title('Pressioni vs Pompate','FontWeight','bold','FontSize',14);

